version: '3'
services:
 frontend:
    container_name: task-manager-frontend
    build:
      context: .
    
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped


